# Generated by Django 4.1.7 on 2023-02-19 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Investimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("investimento", models.TextField(max_length=255)),
                ("valor", models.FloatField()),
                ("pago", models.BooleanField(default=False)),
                (
                    "data",
                    models.DateField(
                        default=datetime.datetime(2023, 2, 19, 10, 48, 10, 718899)
                    ),
                ),
            ],
        ),
    ]
