# Generated by Django 4.1.7 on 2023-02-19 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invista_me", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="investimento",
            name="nivel",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="investimento",
            name="data",
            field=models.DateField(
                default=datetime.datetime(2023, 2, 19, 11, 0, 11, 840443)
            ),
        ),
    ]
