# Generated by Django 4.1.7 on 2023-02-19 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invista_me", "0002_investimento_nivel_alter_investimento_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="investimento",
            name="nivel",
        ),
        migrations.AlterField(
            model_name="investimento",
            name="data",
            field=models.DateField(
                default=datetime.datetime(2023, 2, 19, 11, 1, 38, 521827)
            ),
        ),
    ]
