# Generated by Django 4.1.7 on 2023-02-19 11:01

#import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invista_me", "0002_investimento_nivel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="investimento",
            name="nivel",
        ),
    ]
